import { useEffect, useMemo, useRef, useState } from 'react';
import { AccessibilityInfo, Animated, Pressable, StyleSheet, Text, View } from 'react-native';
import Svg, { G, Polygon } from 'react-native-svg';

import { estimateBuild } from '../lib/brickify';
import { getHeroObjects, type HeroObject } from '../lib/voxelObjects';
import { buildRenderFaces } from '../lib/voxelRender';
import { colors, fonts, inkAlpha, shadow, spacing } from '../theme/tokens';

/**
 * Home hero: real engine-generated sets in full colour, spinning slowly on
 * the saffron world — the "this is what you'll actually get" moment for
 * gift-shoppers. Each set carries a gift-style name and its real kit price
 * (computed from the live parts catalog). Cycles every 5 s; four ticks
 * bottom-left switch sets.
 */

const TAU = Math.PI * 2;
const SPIN_STEP = Math.PI / 90;
const SPIN_INTERVAL_MS = 90;
const OBJECT_INTERVAL_MS = 5000;
const INITIAL_YAW = 0.56;

/** Gift-style display names — these are real sets our engine generated. */
const GIFT_NAMES: Record<string, string> = {
  car: 'THE WEEKEND CAR',
  human: 'MINI-YOU',
  flower: 'FOREVER FLOWER',
  cat: 'MILO THE CAT',
};

/** Real hollow-kit "from" price per hero, from the parts catalog (cached). */
const priceCache = new Map<string, number>();
function fromPriceEur(hero: HeroObject): number {
  let price = priceCache.get(hero.id);
  if (price === undefined) {
    price = estimateBuild(hero.model, hero.accent).hollow.bundleEur;
    priceCache.set(hero.id, price);
  }
  return price;
}

export function BuildPath() {
  const [reduceMotion, setReduceMotion] = useState(false);
  const [yaw, setYaw] = useState(INITIAL_YAW);
  const [objectIndex, setObjectIndex] = useState(0);
  const holdUntil = useRef(0);
  const swap = useRef(new Animated.Value(1)).current;

  useEffect(() => {
    let mounted = true;
    AccessibilityInfo.isReduceMotionEnabled?.()
      .then((enabled) => {
        if (mounted && enabled) setReduceMotion(true);
      })
      .catch(() => undefined);
    return () => {
      mounted = false;
    };
  }, []);

  const changeObject = (next: number | ((current: number) => number)) => {
    // Hidden tabs suspend rAF — swap instantly so the cycle can't freeze mid-fade.
    if (typeof document !== 'undefined' && document.visibilityState === 'hidden') {
      swap.setValue(1);
      setObjectIndex(next);
      return;
    }
    // Outgoing slides left and fades; incoming enters from the right.
    Animated.timing(swap, { duration: 200, toValue: 0, useNativeDriver: true }).start(() => {
      setObjectIndex(next);
      Animated.timing(swap, { duration: 220, toValue: 1, useNativeDriver: true }).start();
    });
  };

  useEffect(() => {
    if (reduceMotion) return;
    const spin = setInterval(() => {
      setYaw((current) => (current + SPIN_STEP) % TAU);
    }, SPIN_INTERVAL_MS);
    const objects = setInterval(() => {
      if (Date.now() < holdUntil.current) return;
      changeObject((current) => (current + 1) % getHeroObjects().length);
    }, OBJECT_INTERVAL_MS);
    return () => {
      clearInterval(spin);
      clearInterval(objects);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reduceMotion]);

  const heroObjects = getHeroObjects();
  const heroObject = heroObjects[objectIndex % heroObjects.length]!;
  const renderFaces = useMemo(
    () => buildRenderFaces(yaw, heroObject.accent, heroObject.model, heroObject.projection),
    [heroObject, yaw],
  );

  const heightCm = useMemo(() => {
    let minJ = Infinity;
    let maxJ = -Infinity;
    for (const voxel of heroObject.model.shell) {
      minJ = Math.min(minJ, voxel.j);
      maxJ = Math.max(maxJ, voxel.j);
    }
    return Math.max(1, Math.round((maxJ - minJ + 1) * 0.96));
  }, [heroObject]);

  const selectObject = (index: number) => {
    holdUntil.current = Date.now() + 12000;
    if (index !== objectIndex % heroObjects.length) changeObject(index);
  };

  const giftName = GIFT_NAMES[heroObject.id] ?? heroObject.label;
  const fromEur = fromPriceEur(heroObject);

  return (
    <View
      accessibilityLabel={`Build showcase: ${giftName.toLowerCase()}, a real ${heroObject.model.brickCount}-brick set generated by the engine, kits from €${Math.round(fromEur)}. Use the ticks below to switch sets.`}
      style={styles.hero}
    >
      <Animated.View
        style={[
          styles.stage,
          {
            opacity: swap,
            transform: [
              { translateX: swap.interpolate({ inputRange: [0, 1], outputRange: [-24, 0] }) },
            ],
          },
        ]}
      >
        <Svg height="100%" viewBox="0 0 320 212" width="100%">
          <G stroke={inkAlpha(0.5)} strokeLinejoin="round" strokeWidth={0.45}>
            {renderFaces.map((face) => (
              <Polygon fill={face.fill} key={face.id} points={face.points} />
            ))}
          </G>
        </Svg>
        <View pointerEvents="none" style={styles.priceChip}>
          <Text style={styles.priceChipLabel}>KITS FROM</Text>
          <Text style={styles.priceChipValue}>€{Math.round(fromEur)}</Text>
        </View>
      </Animated.View>

      <View style={styles.footerRow}>
        <View
          accessibilityLabel="Choose a showcase set"
          accessibilityRole="tablist"
          style={styles.tickRow}
        >
          {heroObjects.map((item, index) => {
            const active = index === objectIndex % heroObjects.length;
            return (
              <Pressable
                accessibilityLabel={GIFT_NAMES[item.id] ?? item.label}
                accessibilityRole="tab"
                accessibilityState={{ selected: active }}
                hitSlop={12}
                key={item.id}
                onPress={() => selectObject(index)}
                style={[styles.tick, active ? styles.tickActive : styles.tickIdle]}
              />
            );
          })}
        </View>
        <View style={styles.caption}>
          <Text style={styles.captionName}>{giftName}</Text>
          <Text style={styles.captionMeta}>
            {heroObject.model.brickCount.toLocaleString('en-US')} BRICKS · {heightCm} CM ·
            GENERATED BY OUR ENGINE
          </Text>
        </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  hero: {
    marginVertical: spacing.md,
    width: '100%',
  },
  stage: {
    aspectRatio: 320 / 212,
    width: '100%',
  },
  priceChip: {
    ...shadow.card,
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    position: 'absolute',
    right: 0,
    top: spacing.sm,
  },
  priceChipLabel: {
    color: inkAlpha(0.55),
    fontFamily: fonts.extrabold,
    fontSize: 9,
    letterSpacing: 1,
  },
  priceChipValue: {
    color: colors.ink,
    fontFamily: fonts.display,
    fontSize: 15,
    fontVariant: ['tabular-nums'],
  },
  footerRow: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  tickRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    minHeight: 44,
  },
  tick: {
    borderRadius: 2,
    height: 6,
  },
  tickActive: {
    backgroundColor: colors.ink,
    width: 22,
  },
  tickIdle: {
    backgroundColor: inkAlpha(0.3),
    width: 10,
  },
  caption: {
    alignItems: 'flex-end',
  },
  captionName: {
    color: colors.ink,
    fontFamily: fonts.display,
    fontSize: 15,
    textTransform: 'uppercase',
  },
  captionMeta: {
    color: inkAlpha(0.66),
    fontFamily: fonts.extrabold,
    fontSize: 11,
    fontVariant: ['tabular-nums'],
    letterSpacing: 0.4,
    marginTop: 2,
  },
});
